"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.external_learning_unit_all_of import ExternalLearningUnitAllOf


class TestExternalLearningUnitAllOf(unittest.TestCase):
    """ExternalLearningUnitAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalLearningUnitAllOf(self):
        """Test ExternalLearningUnitAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalLearningUnitAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
