"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.06
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_enrollment_sdk
from osis_learning_unit_enrollment_sdk.model.attribution_function_enum import AttributionFunctionEnum
from osis_learning_unit_enrollment_sdk.model.learning_unit_attribution_substitute import LearningUnitAttributionSubstitute
globals()['AttributionFunctionEnum'] = AttributionFunctionEnum
globals()['LearningUnitAttributionSubstitute'] = LearningUnitAttributionSubstitute
from osis_learning_unit_enrollment_sdk.model.learning_unit_attribution import LearningUnitAttribution


class TestLearningUnitAttribution(unittest.TestCase):
    """LearningUnitAttribution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLearningUnitAttribution(self):
        """Test LearningUnitAttribution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LearningUnitAttribution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
