"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.education_group_type_enum import EducationGroupTypeEnum


class TestEducationGroupTypeEnum(unittest.TestCase):
    """EducationGroupTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEducationGroupTypeEnum(self):
        """Test EducationGroupTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EducationGroupTypeEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
