"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.06
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_enrollment_sdk
from osis_learning_unit_enrollment_sdk.model.learning_unit_campus import LearningUnitCampus


class TestLearningUnitCampus(unittest.TestCase):
    """LearningUnitCampus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLearningUnitCampus(self):
        """Test LearningUnitCampus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LearningUnitCampus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
