"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.learning_unit_teaching_material import LearningUnitTeachingMaterial


class TestLearningUnitTeachingMaterial(unittest.TestCase):
    """LearningUnitTeachingMaterial unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLearningUnitTeachingMaterial(self):
        """Test LearningUnitTeachingMaterial"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LearningUnitTeachingMaterial()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
