"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.inline_response2001 import InlineResponse2001


class TestInlineResponse2001(unittest.TestCase):
    """InlineResponse2001 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001(self):
        """Test InlineResponse2001"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2001()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
