"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.component_type_enum import ComponentTypeEnum
globals()['ComponentTypeEnum'] = ComponentTypeEnum
from osis_learning_unit_sdk.model.learning_unit_component import LearningUnitComponent


class TestLearningUnitComponent(unittest.TestCase):
    """LearningUnitComponent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLearningUnitComponent(self):
        """Test LearningUnitComponent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LearningUnitComponent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
