"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.learning_unit import LearningUnit
globals()['LearningUnit'] = LearningUnit
from osis_learning_unit_sdk.model.paginated_learning_unit_list_all_of import PaginatedLearningUnitListAllOf


class TestPaginatedLearningUnitListAllOf(unittest.TestCase):
    """PaginatedLearningUnitListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedLearningUnitListAllOf(self):
        """Test PaginatedLearningUnitListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedLearningUnitListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
