"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.learning_unit import LearningUnit
from osis_learning_unit_sdk.model.learning_unit_campus import LearningUnitCampus
from osis_learning_unit_sdk.model.learning_unit_component import LearningUnitComponent
from osis_learning_unit_sdk.model.learning_unit_detailed_all_of import LearningUnitDetailedAllOf
from osis_learning_unit_sdk.model.learning_unit_detailed_all_of_proposal import LearningUnitDetailedAllOfProposal
from osis_learning_unit_sdk.model.learning_unit_subtype_enum import LearningUnitSubtypeEnum
from osis_learning_unit_sdk.model.learning_unit_type_enum import LearningUnitTypeEnum
from osis_learning_unit_sdk.model.periodicity_enum import PeriodicityEnum
from osis_learning_unit_sdk.model.quadrimester_enum import QuadrimesterEnum
globals()['LearningUnit'] = LearningUnit
globals()['LearningUnitCampus'] = LearningUnitCampus
globals()['LearningUnitComponent'] = LearningUnitComponent
globals()['LearningUnitDetailedAllOf'] = LearningUnitDetailedAllOf
globals()['LearningUnitDetailedAllOfProposal'] = LearningUnitDetailedAllOfProposal
globals()['LearningUnitSubtypeEnum'] = LearningUnitSubtypeEnum
globals()['LearningUnitTypeEnum'] = LearningUnitTypeEnum
globals()['PeriodicityEnum'] = PeriodicityEnum
globals()['QuadrimesterEnum'] = QuadrimesterEnum
from osis_learning_unit_sdk.model.learning_unit_detailed import LearningUnitDetailed


class TestLearningUnitDetailed(unittest.TestCase):
    """LearningUnitDetailed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLearningUnitDetailed(self):
        """Test LearningUnitDetailed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LearningUnitDetailed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
