"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.06
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_enrollment_sdk
from osis_learning_unit_enrollment_sdk.model.external_learning_unit_all_of import ExternalLearningUnitAllOf
from osis_learning_unit_enrollment_sdk.model.learning_unit_campus import LearningUnitCampus
from osis_learning_unit_enrollment_sdk.model.learning_unit_component import LearningUnitComponent
from osis_learning_unit_enrollment_sdk.model.learning_unit_detailed import LearningUnitDetailed
from osis_learning_unit_enrollment_sdk.model.learning_unit_detailed_all_of_proposal import LearningUnitDetailedAllOfProposal
from osis_learning_unit_enrollment_sdk.model.learning_unit_subtype_enum import LearningUnitSubtypeEnum
from osis_learning_unit_enrollment_sdk.model.learning_unit_type_enum import LearningUnitTypeEnum
from osis_learning_unit_enrollment_sdk.model.periodicity_enum import PeriodicityEnum
from osis_learning_unit_enrollment_sdk.model.quadrimester_enum import QuadrimesterEnum
globals()['ExternalLearningUnitAllOf'] = ExternalLearningUnitAllOf
globals()['LearningUnitCampus'] = LearningUnitCampus
globals()['LearningUnitComponent'] = LearningUnitComponent
globals()['LearningUnitDetailed'] = LearningUnitDetailed
globals()['LearningUnitDetailedAllOfProposal'] = LearningUnitDetailedAllOfProposal
globals()['LearningUnitSubtypeEnum'] = LearningUnitSubtypeEnum
globals()['LearningUnitTypeEnum'] = LearningUnitTypeEnum
globals()['PeriodicityEnum'] = PeriodicityEnum
globals()['QuadrimesterEnum'] = QuadrimesterEnum
from osis_learning_unit_enrollment_sdk.model.external_learning_unit import ExternalLearningUnit


class TestExternalLearningUnit(unittest.TestCase):
    """ExternalLearningUnit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalLearningUnit(self):
        """Test ExternalLearningUnit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalLearningUnit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
