"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.pagination import Pagination


class TestPagination(unittest.TestCase):
    """Pagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagination(self):
        """Test Pagination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Pagination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
