"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.learning_unit_subtype_enum import LearningUnitSubtypeEnum


class TestLearningUnitSubtypeEnum(unittest.TestCase):
    """LearningUnitSubtypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLearningUnitSubtypeEnum(self):
        """Test LearningUnitSubtypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LearningUnitSubtypeEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
