"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.09
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.learning_unit_summary_specification import LearningUnitSummarySpecification


class TestLearningUnitSummarySpecification(unittest.TestCase):
    """LearningUnitSummarySpecification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLearningUnitSummarySpecification(self):
        """Test LearningUnitSummarySpecification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LearningUnitSummarySpecification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
