"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.09
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.decree_category_enum import DecreeCategoryEnum


class TestDecreeCategoryEnum(unittest.TestCase):
    """DecreeCategoryEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDecreeCategoryEnum(self):
        """Test DecreeCategoryEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DecreeCategoryEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
