"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.component_type_enum import ComponentTypeEnum


class TestComponentTypeEnum(unittest.TestCase):
    """ComponentTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComponentTypeEnum(self):
        """Test ComponentTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ComponentTypeEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
