"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.13
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.api.classe_api import ClasseApi  # noqa: E501


class TestClasseApi(unittest.TestCase):
    """ClasseApi unit test stubs"""

    def setUp(self):
        self.api = ClasseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_classes(self):
        """Test case for get_classes

        """
        pass


if __name__ == '__main__':
    unittest.main()
