"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.learning_unit_campus import LearningUnitCampus
from osis_learning_unit_sdk.model.learning_unit_component import LearningUnitComponent
from osis_learning_unit_sdk.model.learning_unit_detailed_all_of_proposal import LearningUnitDetailedAllOfProposal
from osis_learning_unit_sdk.model.periodicity_enum import PeriodicityEnum
from osis_learning_unit_sdk.model.quadrimester_enum import QuadrimesterEnum
globals()['LearningUnitCampus'] = LearningUnitCampus
globals()['LearningUnitComponent'] = LearningUnitComponent
globals()['LearningUnitDetailedAllOfProposal'] = LearningUnitDetailedAllOfProposal
globals()['PeriodicityEnum'] = PeriodicityEnum
globals()['QuadrimesterEnum'] = QuadrimesterEnum
from osis_learning_unit_sdk.model.learning_unit_detailed_all_of import LearningUnitDetailedAllOf


class TestLearningUnitDetailedAllOf(unittest.TestCase):
    """LearningUnitDetailedAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLearningUnitDetailedAllOf(self):
        """Test LearningUnitDetailedAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LearningUnitDetailedAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
