"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.periodicity_enum import PeriodicityEnum


class TestPeriodicityEnum(unittest.TestCase):
    """PeriodicityEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeriodicityEnum(self):
        """Test PeriodicityEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PeriodicityEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
