"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_sdk
from osis_learning_unit_sdk.model.decree_category_enum import DecreeCategoryEnum
from osis_learning_unit_sdk.model.duration_unit_enum import DurationUnitEnum
from osis_learning_unit_sdk.model.education_group_type_enum import EducationGroupTypeEnum
globals()['DecreeCategoryEnum'] = DecreeCategoryEnum
globals()['DurationUnitEnum'] = DurationUnitEnum
globals()['EducationGroupTypeEnum'] = EducationGroupTypeEnum
from osis_learning_unit_sdk.model.education_group_root import EducationGroupRoot


class TestEducationGroupRoot(unittest.TestCase):
    """EducationGroupRoot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEducationGroupRoot(self):
        """Test EducationGroupRoot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EducationGroupRoot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
