"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.06
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_enrollment_sdk
from osis_learning_unit_enrollment_sdk.model.learning_unit_achievement import LearningUnitAchievement


class TestLearningUnitAchievement(unittest.TestCase):
    """LearningUnitAchievement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLearningUnitAchievement(self):
        """Test LearningUnitAchievement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LearningUnitAchievement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
