"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.09
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from osis_learning_unit_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from osis_learning_unit_sdk.model.learning_unit_subtype_enum import LearningUnitSubtypeEnum
    from osis_learning_unit_sdk.model.learning_unit_type_enum import LearningUnitTypeEnum
    globals()['LearningUnitSubtypeEnum'] = LearningUnitSubtypeEnum
    globals()['LearningUnitTypeEnum'] = LearningUnitTypeEnum


class LearningUnit(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'url': (str,),  # noqa: E501
            'osis_url': (str,),  # noqa: E501
            'acronym': (str,),  # noqa: E501
            'credits': (str,),  # noqa: E501
            'status': (bool,),  # noqa: E501
            'has_proposal': (bool, none_type,),  # noqa: E501
            'has_classes': (bool,),  # noqa: E501
            'title': (str,),  # noqa: E501
            'type': (LearningUnitTypeEnum,),  # noqa: E501
            'type_text': (str,),  # noqa: E501
            'subtype': (LearningUnitSubtypeEnum,),  # noqa: E501
            'subtype_text': (str,),  # noqa: E501
            'requirement_entity': (str,),  # noqa: E501
            'allocation_entity': (str,),  # noqa: E501
            'academic_year': (int,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'url': 'url',  # noqa: E501
        'osis_url': 'osis_url',  # noqa: E501
        'acronym': 'acronym',  # noqa: E501
        'credits': 'credits',  # noqa: E501
        'status': 'status',  # noqa: E501
        'has_proposal': 'has_proposal',  # noqa: E501
        'has_classes': 'has_classes',  # noqa: E501
        'title': 'title',  # noqa: E501
        'type': 'type',  # noqa: E501
        'type_text': 'type_text',  # noqa: E501
        'subtype': 'subtype',  # noqa: E501
        'subtype_text': 'subtype_text',  # noqa: E501
        'requirement_entity': 'requirement_entity',  # noqa: E501
        'allocation_entity': 'allocation_entity',  # noqa: E501
        'academic_year': 'academic_year',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """LearningUnit - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            url (str): [optional]  # noqa: E501
            osis_url (str): [optional]  # noqa: E501
            acronym (str): [optional]  # noqa: E501
            credits (str): [optional]  # noqa: E501
            status (bool): [optional]  # noqa: E501
            has_proposal (bool, none_type): [optional]  # noqa: E501
            has_classes (bool): [optional]  # noqa: E501
            title (str): [optional]  # noqa: E501
            type (LearningUnitTypeEnum): [optional]  # noqa: E501
            type_text (str): [optional]  # noqa: E501
            subtype (LearningUnitSubtypeEnum): [optional]  # noqa: E501
            subtype_text (str): [optional]  # noqa: E501
            requirement_entity (str): [optional]  # noqa: E501
            allocation_entity (str): [optional]  # noqa: E501
            academic_year (int): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
