# flake8: noqa

"""
    Learning Unit Service

    A set of API endpoints that allow you to get information about learning unit  # noqa: E501

    The version of the OpenAPI document: 1.11
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.11"

# import ApiClient
from osis_learning_unit_sdk.api_client import ApiClient

# import Configuration
from osis_learning_unit_sdk.configuration import Configuration

# import exceptions
from osis_learning_unit_sdk.exceptions import OpenApiException
from osis_learning_unit_sdk.exceptions import ApiAttributeError
from osis_learning_unit_sdk.exceptions import ApiTypeError
from osis_learning_unit_sdk.exceptions import ApiValueError
from osis_learning_unit_sdk.exceptions import ApiKeyError
from osis_learning_unit_sdk.exceptions import ApiException
